### ISSUE TITLE
Explain difference between UPDI and PROG input

### ISSUE THREAD

**Issue by larsfcfa** [Dlloydev/Updi-Key#1]
Hello Folks,

I can't get the clue, what is the difference between 
J3-1 | UPDI-HOST | I/O | Updi-Key UPDI
J3-3 | PROG | I/O | Updi-Key UPDI programming pin

My UPDI-programmer has 3 connector: 
VGT(VCC) =5V
GND
UPDI
I would connect the UPDI-output of my UPDI-programmer to the J3-1  UPDI-HOST Pin.
But what is PROG? Could you please explain?

**Comment by larsfcfa** [comment]
#Question: what is PROG for
`label:question`

**Comment by Dlloydev** [comment]
Hi,

- `PROG` is directly connected to the `PA0` pin of the Attiny202 and is used to "program" the Updi-Key programmer (for firmware updates).
- `UPDI-HOST` is the UPDI input signal to the Updi-Key.
-  `HVUPDI-TARGET` is the target UPDI that includes the 12V pulse and the NVMPROG key code to the UPDI signal as necessary

**Comment by larsfcfa** [comment]
Thank you, thus PROG is the UPDI-Connect to the ATtiny212 for FW update.
Now it's clear!
